# Generated by Django 5.0.4 on 2024-05-05 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_payment_expiration_date_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 15, 0, 23, 274453)),
        ),
    ]
